runtime: nodejs18

env_variables:
  # Application
  NAME: 'api-pessoas'
  VERSION: '1.0.0'
  NODE_ENV: 'develop'
  # DATABASE
  DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
  # EXTERNAL
  API_AUTENTICACAO: ${API_AUTENTICACAO}
  API_ENDERECOS: ${API_ENDERECOS}